### ISSUE TITLE
Add a shell script to install the dependancies for manual build (using deb package)

### ISSUE THREAD

**Issue by rushabh-v** [rushabh-v/linux_face_unlock#13]

**Comment by pulkitvyas08** [comment]
I will be working on this before moving on to writing tests. Please assign this issue to me

**Comment by adarshkushwah** [comment]
Hi, does this means that the shell script is supposed to install all the missing package dependencies when one tries to install the facerec package using dpkg?

**Comment by pulkitvyas08** [comment]
Yes that's exactly it

**Comment by pulkitvyas08** [comment]
let's close this for now. Will reopen if we find any new way of doing this
