### ISSUE TITLE
Easily unlocked by different face

### ISSUE THREAD

**Issue by exander77** [rushabh-v/linux_face_unlock#2]
My girlfriend's face unlocks it as well as mine.

**Comment by rushabh-v** [comment]
Thanks for reporting it @exander77 
Right now I have trained a classification model but I think it would be better to use a regressive model.
I will come with a commit soon.

**Comment by rushabh-v** [comment]
@exander77  I found my mistake. In this commit (e957be694d0f6d73bcd873c1ac4f2fb6ffbcbd3f), I forced the training pictures(the pictures of the root user) to be converted into gray, but I forgot to convert the pictures of other people that are being used for training( the pictures that are there in the images.zip file). 


So right now it was classifying every gray image as root and every colorful image as non-root and when you try to unlock your device, by default it converts your images to gray. So all the person would be classified as root.

I have updated the images.zip file, and also added some more security features. It works absolutely fine on my machine. Can you please install it again and tell me if you face any problem?

Thanks again : )

**Comment by rushabh-v** [comment]
you will need to delete the "~/linux_face_unlock" and "/lib/Auth" by running `sudo rm -r linux_face_unlock` and `sudo rm -r /lib/Auth` respectively. And then you can install it again according the installation steps.

**Comment by rushabh-v** [comment]
@exander77  you can close this issue if your problem is resolved now...
