### ISSUE TITLE
Information on Security of Implementation

### ISSUE THREAD

**Issue by Amarjit3** [rushabh-v/linux_face_unlock#27]
Hello, I am interested in your app and had a couple of questions. I read your post on Medium with interest.

How secure is the app - can it be fooled with a picture for example? Or does it build a 3D model of the face?
Does it use the infrared camera sensor like Howdy does?

Many thanks in advance.

**Comment by rushabh-v** [comment]
Hi @Amarjit3. Thanks for your interest.

Yes, it's possible to fool it using a picture. and it does not use 3D techniques or infrared sensors. The aim of this software is only to make authentication easier, a person with big security concerns should not use it.

By security (in the blog) I mean it's not possible to edit the scripts locally to make trespassing possible.

Let me know if you have any other doubts, thanks.

**Comment by rushabh-v** [comment]
Closing this. Feel free to reach out if you have any other doubts.
